// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ABreadcrumb: typeof import('ant-design-vue/es')['Breadcrumb']
    ABreadcrumbItem: typeof import('ant-design-vue/es')['BreadcrumbItem']
    AButton: typeof import('ant-design-vue/es')['Button']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    'AntDesign:downOutlined': typeof import('~icons/ant-design/down-outlined')['default']
    'AntDesign:fullscreenExitOutlined': typeof import('~icons/ant-design/fullscreen-exit-outlined')['default']
    'AntDesign:fullscreenOutlined': typeof import('~icons/ant-design/fullscreen-outlined')['default']
    'AntDesign:lockOutlined': typeof import('~icons/ant-design/lock-outlined')['default']
    'AntDesign:menuFoldOutlined': typeof import('~icons/ant-design/menu-fold-outlined')['default']
    'AntDesign:menuUnfoldOutlined': typeof import('~icons/ant-design/menu-unfold-outlined')['default']
    'AntDesign:userOutlined': typeof import('~icons/ant-design/user-outlined')['default']
    ASpace: typeof import('ant-design-vue/es')['Space']
    ASubMenu: typeof import('ant-design-vue/es')['SubMenu']
    ATag: typeof import('ant-design-vue/es')['Tag']
    BasicForm: typeof import('./components/form/src/basic-form.vue')['default']
    Breadcrumb: typeof import('./components/breadcrumb/index.vue')['default']
    FormItem: typeof import('./components/form/src/components/form-item.vue')['default']
    FullScreen: typeof import('./components/full-screen/index.vue')['default']
    Hamburger: typeof import('./components/hamburger/index.vue')['default']
    IconContainer: typeof import('./components/icon-container/index.vue')['default']
    SearchInput: typeof import('./components/search-input/index.vue')['default']
  }
}

export { }
